- name: exam-iac
  gather_facts: false
  hosts: [all]
  become: yes

  tasks:

    - name: Create exam-iac
      docker_container:
        name: exam-iac
        image: sturyk/exam-iac
        pull: true
        state: started
        ports:
          - "8080:8080"